### ISSUE TITLE
Add treetime as direct pip3 install?

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/docker-base#134]
### Context
I've tried to get `treetime` included in the list of tools that should have consistent versions across docker builds.

The reasoning is that `treetime` is a core Nextstrain component that we should always use the latest version of. Docker builds should be redone when there's a new treetime version.

Right now, treetime gets installed via Augur. I was wondering whether that is sufficient or not - and whether there would be benefit in having it as a separate top level pip install.

**Comment by tsibley** [comment]
I'd definitely be ok including TreeTime as a first-order dep. I don't necessarily think it's vital to do so, though maybe don't have all the context there.

TreeTime is currently sort of treated like "friends and family" of Nextstrain, not a fully core/first-party component, but not a fully third-party component either.¹ I think the umbrella of Nextstrain hasn't been applied to TreeTime largely for some combination of historical reasons (e.g. it predates Augur, started in Richard's group, and the repo is still housed under https://github.com/neherlab) and the general lack of familiarity with it from the Blab dev team because of that (and also because it's more "hard" science/math and less systems integration).

¹ That's not to devalue it! Clearly TreeTime is a critical and fundamental part of using Augur and Nextstrain.

**Comment by joverlee521** [comment]
Do we have to be worried about the direct install overriding the version pinned for Augur?

**Comment by victorlin** [comment]
@joverlee521 If TreeTime is unpinned or installed before Augur is installed, the version requirements in Augur's setup.py will be applied. Examples:

```sh
pip install nextstrain-augur
pip install phylo-treetime # no effect – package is already installed
```

```sh
pip install phylo-treetime==0.8.6
pip install nextstrain-augur  # uninstalls TreeTime 0.8.6 and installs 0.9.5
```

**Comment by joverlee521** [comment]
Thanks @victorlin! 

That means we would always install the version that's pinned in Augur rather than the latest version of `treetime`. 
So what would be the purpose of making the direct install?

**Comment by victorlin** [comment]
@joverlee521 see 64d770bc15914fddc3e9ca0f25ebb676dd4119ec for the best reason I could come up with.

**Comment by corneliusroemer** [comment]
A further reason is that if we install it directly, it becomes available in the path (someone mentioned if it's installed as dependency this isn't the case).

**Comment by victorlin** [comment]
@corneliusroemer actually, only 883e40c4b7e194338cbe9dd98a9434ee3d291de0 is necessary for the executable to become available in the path. No need to direct install, but I think it makes more sense to do so if copying the executable explicitly.
