### ISSUE TITLE
Epic: Work towards using more recent Snakemake version

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/docker-base#135]
### Context

We currently pin Snakemake to version 5.10.0, which is more than 3 years old.

I think the reasoning was that after that version, a bug/change was introduced that made certain workflows of ours not work with versions higher than 5.10.0

I usually use latest Snakemake in my work and don't encounter issues. So either this bug has been resolved now, or the way we use Snakemake is arcane and no longer supported by current Snakemake.

While pinning Snakemake may not be a bad idea, given Snakemake's tendency for unexpected breaking changes, this version should be updated regularly to something not too old.

I've seen discussions where we couldn't use some new Snakemake feature because we were using 5.10.0. I'm sure there are other reasons not to use an old version.

### Description

It may well be that if we were to start using a more recent version like 7.20, some workflows using the latest docker builds break.

So we should test our major workflows before making a change to Snakemake version so we see how much would have to be changed.

For no-longer updated workflows, they can just use old docker builds - that's the beauty of docker.

Any thoughts @joverlee521 @tsibley @huddlej @victorlin @j23414?

**Comment by tsibley** [comment]
> While pinning Snakemake may not be a bad idea, given Snakemake's tendency for unexpected breaking changes, this version should be updated regularly to something not too old.

Agreed that we should aim to update regularly, but I think pinning is _necessary_ given how often Snakemake breaks stuff.

In any case, upgrading Snakemake should be much safer for users now since the release of Nextstrain CLI [4.0.0 (June 2022)](https://github.com/nextstrain/cli/blob/f3158208f1808898e85277fafcb793c9cd95fa94/CHANGES.md#400-24-june-2022), as long as they're using that version or newer.

We should still test in advance, for sure.

It would be good to put the nice rationale in this PR into the actual commit message (i.e. of 8530204). (More minor, but we also don't use the `chore(deps)` notation in this repo (and many other Nextstrain repos).)

**Comment by tsibley** [comment]
> making workflows fail/not run at all due to some deeper syntax changes.

There are many other breaking changes in the versions. I'm obviously not aware of all changes, but I don't know of any that break the workflow entirely, just ones that break bits of it. That said, a break is a break, and some users will surely encounter issues that stop them after upgrading.

>  Tests would be done by running our standard builds but with image overriden with the image produced by this PR.

Yep.

**Comment by corneliusroemer** [comment]
I've started testing with the snakemake 7.24.1 image. ncov open builds seem to work - that's good, as I was most worried about ncov. When I run workflows locally, I usually use the latest snakemake version, so things like mpox, ingest etc should be fine. Though we should still test.

I expect breakage to be the workflow failing to run - not to produce incorrect results (as Snakemake mostly orchestrates). So if it doesn't fail, we should be good.
