### ISSUE TITLE
ENH: Cache build across commit/branch?

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/docker-base#137]
### Context
For some reason the "branch" build of this PR failed (apparently something temporary with the action): https://github.com/nextstrain/docker-base/actions/runs/4403292997/attempts/1

However, the "commit" build worked.

I was wondering why the successfully completed "commit" build is not used for the "branch build" now that I'm rerunning the "branch" build. Aren't the two builds identical? Am I missing some crucial difference between them?

All up to ~ pip install of aws cli was cached, but afterward redid on rerun: https://github.com/nextstrain/docker-base/actions/runs/4403292997/jobs/7714307715

**Comment by victorlin** [comment]
First, to clarify - I assume you are talking about the `pull_request` ("branch") vs. `push` ("commit") triggered CI runs. Both get run on every change pushed to a PR.

> Aren't the two builds identical?

Most of the times, yes they will be identical or at least have much overlap in terms of layers. Differences come if the target branch has newer changes, since the `push` trigger has contents from just the PR source branch, while the `pull_request` trigger is effectively a merge of the source branch and target branch.

The `pull_request`-triggered run isn't pushed to Docker Hub, so there's no way to source it for caching. I believe the reason for its existence is to test PRs from forks which don't have access to push to Docker Hub. Only the `push`-triggered run is pushed to Docker Hub.

Since each run works independently on separate tags (e.g. `branch-snakemake-7.24.1` vs. `branch-136-merge`), I don't think it's worth writing logic to communicate the tags between CI runs for slight improvements in cache time, if any.

---

As an aside, I think there's a flaw in how `--cache-from` is used:

https://github.com/nextstrain/docker-base/blob/852036ec9355aa98adeac5027acdfd581eda5020/.github/workflows/ci.yml#L43

https://github.com/nextstrain/docker-base/blob/852036ec9355aa98adeac5027acdfd581eda5020/devel/build#L63-L64

We are currently using `ghcr.io` as a transient registry (images are deleted at the end of each CI run), so we shouldn't use it for caching. Instead, we should cache from the final destination registry (`docker.io`).

I'll make a PR to fix this.
